# Config file for automatic testing at travis-ci.org

stages:
  - format
  - test

language: python

jobs:
  include:
    - stage: format
      name: "Black format check"
      python: "3.7"
      install: pip install black
      script:
        - black --version
        - black . --check
      after_success: ""

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=django-22
  - DJANGO_VERSION=django-30

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION | tr -d .)

after_success:
  - coveralls
