# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=django-22
  - DJANGO_VERSION=django-30

install: pip install -r requirements_test.txt
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION | tr -d .)

jobs:
  include:
    - stage: format
      python: 3.7
      script: black --check

after_success:
  - coveralls
