# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION=django-22

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION | tr -d .)

after_success:
  - coveralls
